### ISSUE TITLE
Define "Je veux" as a variable

### ISSUE THREAD

**Issue by qk7b** [GeebToo/GeebTweet#2]
What if I want to display all the tweets starting by "I want" or any other thing but not "Je veux".
It would be great to make it customizable.

**Comment by GeebToo** [comment]
Don't worry, this is the next step.

**Comment by GeebToo** [comment]
With the release [1.1.0](https://github.com/GeebToo/GeebTweet/releases/tag/1.1.0) you can display all the tweets starting by what you want. Enjoy !
